/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package product.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Product service. Represents a row in the &quot;catalog_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link product.service.model.impl.ProductModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link product.service.model.impl.ProductImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Product
 * @see product.service.model.impl.ProductImpl
 * @see product.service.model.impl.ProductModelImpl
 * @generated
 */
@ProviderType
public interface ProductModel extends BaseModel<Product> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product model instance should use the {@link Product} interface instead.
	 */

	/**
	 * Returns the primary key of this product.
	 *
	 * @return the primary key of this product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product.
	 *
	 * @param primaryKey the primary key of this product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this product.
	 *
	 * @return the uuid of this product
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this product.
	 *
	 * @param uuid the uuid of this product
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the product ID of this product.
	 *
	 * @return the product ID of this product
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product.
	 *
	 * @param productId the product ID of this product
	 */
	public void setProductId(long productId);

	/**
	 * Returns the name of this product.
	 *
	 * @return the name of this product
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this product.
	 *
	 * @param name the name of this product
	 */
	public void setName(String name);

	/**
	 * Returns the description of this product.
	 *
	 * @return the description of this product
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this product.
	 *
	 * @param description the description of this product
	 */
	public void setDescription(String description);

	/**
	 * Returns the price of this product.
	 *
	 * @return the price of this product
	 */
	public int getPrice();

	/**
	 * Sets the price of this product.
	 *
	 * @param price the price of this product
	 */
	public void setPrice(int price);

	/**
	 * Returns the sku of this product.
	 *
	 * @return the sku of this product
	 */
	@AutoEscape
	public String getSku();

	/**
	 * Sets the sku of this product.
	 *
	 * @param sku the sku of this product
	 */
	public void setSku(String sku);

	/**
	 * Returns the ratings of this product.
	 *
	 * @return the ratings of this product
	 */
	public int getRatings();

	/**
	 * Sets the ratings of this product.
	 *
	 * @param ratings the ratings of this product
	 */
	public void setRatings(int ratings);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(product.service.model.Product product);

	@Override
	public int hashCode();

	@Override
	public CacheModel<product.service.model.Product> toCacheModel();

	@Override
	public product.service.model.Product toEscapedModel();

	@Override
	public product.service.model.Product toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}